
# +------------------------------------------------------------+
# | UI THEME (LOOK & FEEL)                                     |
# +------------------------------------------------------------+

# Core Colors
COLOR__WINDOW_OUTLINE = "#606060"
COLOR__HARD = "#202020"
COLOR__HARDER = "#1f1f1f"
COLOR_HARDEST = "#171717"
COLOR__SOFT = "#272727"
COLOR__SOFTEST = "#2c2c2c"
COLOR__DANGER = "#c42b1c"
COLOR__SEPARATORS = "#323131"

COLOR__TEXT = "white"
COLOR__TEXT_MUTED = "#707070"

# Pseudo-State Colors
COLOR__HOVER__PRIMARY = "#2e2d2b"
COLOR__HOVER__SECONDARY = "#383838"
COLOR__PRESSED_PRIMARY = "#2a2927"
COLOR__PRESSED_SECONDARY = "#343434"

# Default Font
FONT_STYLE = "normal"
FONT_WEIGHT = "normal"
FONT_FAMILY = "Segoe UI Variable"

# Forms
FONT_WEIGHT__FORM__PRIMARY = "bold"
FONT_WEIGHT__FORM__SECONDARY = "normal"

COLOR__FORM_BUTTON__DEFAULT = "#252525"
COLOR__FORM_BUTTON__HOVERED = "#2a2a2a"
COLOR__FORM_BUTTON__PRESSED = "#1e1e1e"

COLOR__FORM_BUTTON_TEXT__DEFAULT = "white"
COLOR__FORM_BUTTON_TEXT__HOVERED = "white"
COLOR__FORM_BUTTON_TEXT__PRESSED = "#cccccc"

COLOR__FORM_BUTTON_BORDER__DEFAULT = "#272727"
COLOR__FORM_BUTTON_BORDER__HOVERED = "#272727"
COLOR__FORM_BUTTON_BORDER__PRESSED = "#272727"

COLOR__FORM_FIELD__DEFAULT = "#2d2d2d"
COLOR__FORM_FIELD__HOVERED = "#323232"
COLOR__FORM_FIELD__FOCUSED = "#1f1f1f"

COLOR__FORM_FIELD_TEXT__DEFAULT = "white"
COLOR__FORM_FIELD_TEXT__HOVERED = "white"
COLOR__FORM_FIELD_TEXT__FOCUSED = "white"

COLOR__FORM_FIELD_BORDERS__DEFAULT = "#1d1d1d"
COLOR__FORM_FIELD_BORDERS__HOVERED = "#1d1d1d"
COLOR__FORM_FIELD_BORDERS__FOCUSED = "#303030"

COLOR__FORM_FIELD_ACCENT__DEFAULT = "#9a9a9a"
COLOR__FORM_FIELD_ACCENT__HOVERED = "#9a9a9a"
COLOR__FORM_FIELD_ACCENT__FOCUSED = "#4cc2ff"

# +------------------------------------------------------------+
# | UI DIMENSIONS                                              |
# +------------------------------------------------------------+

# Padding
DIMENSION__MENU_BUTTON_PADDING_HORIZONTAL = 10
DIMENSION__MENU_BUTTON_PADDING_VERTICAL = 5
DIMENSION__FORM_ELEMENT_PADDING_HORIZONTAL = 8
DIMENSION__FORM_ELEMENT_PADDING_VERTICAL = 3

# Roundness
DIMENSION__WINDOW_BORDER_RADIUS = 11
DIMENSION__BUTTONS_BORDER_RADIUS = 6

# Button Dimensions
DIMENSION__MENU_BUTTON_WIDTH = 45
DIMENSION__MENU_BUTTON_HEIGHT = 30
DIMENSION__WINDOW_BUTTONS_WIDTH = 45
DIMENSION__WINDOW_BUTTONS_HEIGHT = 30

# Bar Heights
DIMENSION__TITLE_BAR_HEIGHT = 32
DIMENSION__STATUS_BAR_HEIGHT = 30

# Font Sizes
FONT_SIZE_PX__TITLE = 13
FONT_SIZE_PX__MENU_ITEM = 16
FONT_SIZE_PX__SUBMENU_ITEM = 14

FONT_SIZE_PX__TEXT_SMALLER = 8
FONT_SIZE_PX__TEXT_SMALL = 12
FONT_SIZE_PX__TEXT = 14
FONT_SIZE_PX__TEXT_BIG = 18
FONT_SIZE_PX__TEXT_BIGGER = 22
FONT_SIZE_PX__TEXT_LARGE = 26

# Form Element Restrictions
DIMENSION__FORM_INPUT_WIDGET_MIN_WIDTH = 100
DIMENSION__FORM_INPUT_WIDGET_MAX_WIDTH = 240

DIMENSION__FORM_DISPLAY_WIDGET_MIN_WIDTH = 100
DIMENSION__FORM_DISPLAY_WIDGET_MAX_WIDTH = 9999
