
# WINDOW
COLOR__WINDOW_FILL = "#202020"
COLOR__WINDOW_OUTLINE = "#606060"
DIMENSION__WINDOW_BORDER_RADIUS = 11

# WINDOW UI
COLOR__UI_TEXT = "white"
FONT_STYLE__UI = "normal"
FONT_WEIGHT__UI = "normal"
FONT_FAMILY__UI = "Segoe UI Variable"

# TITLE BAR
COLOR__TITLE_BAR = "#202020"
COLOR__TITLE_BAR_BUTTON = "transparent"
COLOR__TITLE_BAR_TITLE_TEXT = "#fff"
COLOR__TITLE_BAR_BUTTON__HOVERED = "#2e2d2b"
COLOR__TITLE_BAR_BUTTON_TEXT = "#707070"
COLOR__TITLE_BAR_BUTTON_TEXT__HOVERED = "#fff"
COLOR__TITLE_BAR_CLOSE_BUTTON = "transparent"
COLOR__TITLE_BAR_CLOSE_BUTTON__HOVERED = "#c42b1c"
COLOR__TITLE_BAR_CLOSE_BUTTON_TEXT = "#707070"
COLOR__TITLE_BAR_CLOSE_BUTTON_TEXT__HOVERED = "#fff"
DIMENSION__TITLE_BAR_HEIGHT = 32
DIMENSION__TITLE_BAR_BUTTON_WIDTH = 45
DIMENSION__TITLE_BAR_BUTTON_HEIGHT = 30
DIMENSION__TITLE_BAR_CLOSE_BUTTON_WIDTH = 45
DIMENSION__TITLE_BAR_CLOSE_BUTTON_HEIGHT = 30
FONT_SIZE__TITLE_BAR_TITLE = 13

# MENU BAR
COLOR__MENU_BAR = "#202020"
COLOR__MENU_BAR_ITEM_TEXT = "#fff"
COLOR__MENU_BAR_ITEM__HOVERED = "#2e2d2b"
COLOR__MENU_BAR_ITEM__PRESSED = "#2a2927"
DIMENSION__MENU_BAR_BORDER_RADIUS = 6
FONT_SIZE__MENU_BAR_ITEM = 16

# SUBMENU
COLOR__SUBMENU = "#2c2c2c"
COLOR__SUBMENU_ITEM__HOVERED = "#383838"
COLOR__SUBMENU_ITEM__PRESSED = "#343434"

# STATUS BAR
COLOR__STATUS_BAR = "#1f1f1f"
COLOR__STATUS_BAR_TEXT = "#fff"
DIMENSION__STATUS_BAR_HEIGHT = 30

# MISC
COLOR__SEPARATORS = "#323131"
COLOR__TEXT_EDIT = "#272727"

# FORMS
COLOR__FORM_LABEL_TEXT = "white"
COLOR__FORM_ELEMENT_LABEL_TEXT = "white"

COLOR__FORM_LINE_EDIT__IDLE = "#2d2d2d"
COLOR__FORM_LINE_EDIT__ACTIVE = "#1f1f1f"
COLOR__FORM_LINE_EDIT_TEXT__IDLE = "white"
COLOR__FORM_LINE_EDIT_TEXT__ACTIVE = "white"
COLOR__FORM_LINE_EDIT_BORDER_IDLE = "#303030"
COLOR__FORM_LINE_EDIT_BORDER_ACTIVE = "#303030"
COLOR__FORM_LINE_EDIT_BORDER_BOTTOM_IDLE = "#9a9a9a"
COLOR__FORM_LINE_EDIT_BORDER_BOTTOM_ACTIVE = "#4cc2ff"

COLOR__FORM_LIST_WIDGET__IDLE = COLOR__FORM_LINE_EDIT__IDLE
COLOR__FORM_LIST_WIDGET__ACTIVE = COLOR__FORM_LINE_EDIT__ACTIVE
COLOR__FORM_LIST_WIDGET_TEXT__IDLE = COLOR__FORM_LINE_EDIT_TEXT__IDLE
COLOR__FORM_LIST_WIDGET_TEXT__ACTIVE = COLOR__FORM_LINE_EDIT_TEXT__ACTIVE
COLOR__FORM_LIST_WIDGET_BORDER_IDLE = COLOR__FORM_LINE_EDIT_BORDER_IDLE
COLOR__FORM_LIST_WIDGET_BORDER_ACTIVE = COLOR__FORM_LINE_EDIT_BORDER_ACTIVE
COLOR__FORM_LIST_WIDGET_BORDER_BOTTOM_IDLE = COLOR__FORM_LINE_EDIT_BORDER_BOTTOM_IDLE
COLOR__FORM_LIST_WIDGET_BORDER_BOTTOM_ACTIVE = COLOR__FORM_LINE_EDIT_BORDER_BOTTOM_ACTIVE

FONT_SIZE__FORM_LABEL = 14
