
# +------------------------------------------------------------+
# | UI THEME (LOOK & FEEL)                                     |
# +------------------------------------------------------------+

# Core Colors
COLOR__WINDOW_OUTLINE = "#606060"
COLOR__HARD = "#202020"
COLOR__HARDEST = "#1f1f1f"
COLOR__SOFT = "#272727"
COLOR__SOFTEST = "#2c2c2c"
COLOR__DANGER = "#c42b1c"
COLOR__SEPARATORS = "#323131"

COLOR__TEXT = "white"
COLOR__TEXT_MUTED = "#707070"

# Pseudo-State Colors
COLOR__HOVER__PRIMARY = "#2e2d2b"
COLOR__HOVER__SECONDARY = "#383838"
COLOR__PRESSED_PRIMARY = "#2a2927"
COLOR__PRESSED_SECONDARY = "#343434"

# Default Font
FONT_STYLE = "normal"
FONT_WEIGHT = "normal"
FONT_FAMILY = "Segoe UI Variable"

# Forms
COLOR__FIELD_IDLE = "#2d2d2d"
COLOR__FIELD_SELECTED = "#1f1f1f"
COLOR__FIELD_TEXT_IDLE = "white"
COLOR__FIELD_TEXT_SELECTED = "white"
COLOR__FIELD_BORDERS_IDLE = "#1d1d1d"
COLOR__FIELD_BORDERS_SELECTED = "#303030"
COLOR__FIELD_ACCENT_IDLE = "#9a9a9a"
COLOR__FIELD_ACCENT_SELECTED = "#4cc2ff"

# +------------------------------------------------------------+
# | UI DIMENSIONS                                              |
# +------------------------------------------------------------+

# Padding
DIMENSION__MENU_BUTTON_PADDING_HORIZONTAL = 10
DIMENSION__MENU_BUTTON_PADDING_VERTICAL = 5
DIMENSION__BUTTON_PADDING_HORIZONTAL = 8
DIMENSION__BUTTON_PADDING_VERTICAL = 3

# Roundness
DIMENSION__WINDOW_BORDER_RADIUS = 11
DIMENSION__BUTTONS_BORDER_RADIUS = 6

# Button Dimensions
DIMENSION__MENU_BUTTON_WIDTH = 45
DIMENSION__MENU_BUTTON_HEIGHT = 30
DIMENSION__WINDOW_BUTTONS_WIDTH = 45
DIMENSION__WINDOW_BUTTONS_HEIGHT = 30

# Bar Heights
DIMENSION__TITLE_BAR_HEIGHT = 32
DIMENSION__STATUS_BAR_HEIGHT = 30

# Font Sizes
FONT_SIZE_PX__TITLE = 13
FONT_SIZE_PX__MENU_ITEM = 16
FONT_SIZE_PX__SUBMENU_ITEM = 14

FONT_SIZE_PX__TEXT_SMALLER = 8
FONT_SIZE_PX__TEXT_SMALL = 12
FONT_SIZE_PX__TEXT = 16
FONT_SIZE_PX__TEXT_BIG = 18
FONT_SIZE_PX__TEXT_BIGGER = 22
FONT_SIZE_PX__TEXT_LARGE = 26

# Form Element Restrictions
DIMENSION__BUTTON_MIN_WIDTH = 40
DIMENSION__BUTTON_MAX_WIDTH = 160

DIMENSION__LINE_EDIT_MIN_WIDTH = 150
DIMENSION__LINE_EDIT_MAX_WIDTH = 600

DIMENSION__LIST_MIN_WIDTH = 100
DIMENSION__LIST_MAX_WIDTH = 9999
